# Generated by Django 4.2 on 2024-11-27 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='naiyo',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='naiyo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='syosai',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='syosai'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
